### ISSUE TITLE
A JNI error has occurred, please check your installation and try again

### ISSUE THREAD

**Issue by wilhelmzeuschner** [davetcc/tcMenu#7]
Sadly I cannot launch the program.
My error message:
![ERROR](https://user-images.githubusercontent.com/37621765/40686320-3c4317f2-6397-11e8-9b0e-3e03ec301c11.PNG)
Java Installation:
![Java Installation](https://user-images.githubusercontent.com/37621765/40686321-3c5ad612-6397-11e8-9784-9b6ff3f72d31.PNG)

I found this: [https://stackoverflow.com/questions/22381202/a-jni-error-has-occurred-please-check-your-installation-and-try-again-in-eclips](https://stackoverflow.com/questions/22381202/a-jni-error-has-occurred-please-check-your-installation-and-try-again-in-eclips)

**Comment by davetcc** [comment]
That is strange, there is JNI in the project for the rs232 support but it shouldn’t even be initialised in the designer as it doesnt use It. I’m wondering if it’s because I’ve inadvertently used a Java 9 feature as the compile JDK was v9 set to 1.8 compatibility. I’ll install JDK8 on my windows machine when I get back to my office today and test it then update this issue. 

I’ve seen similar before under those circumstances, to be honest all the testing has been on jdk9 and JDK10 on a mix of macOS high Sierra and windows 10.  

If that is the case I’ll run the build again on 1.8. Sorry about this.

**Comment by wilhelmzeuschner** [comment]
OK, thanks.

**Comment by davetcc** [comment]
I’ve recreated and  tracked down the problem. Until I get chance to rebuild the package it’s only compatible with java 9 upwards. I’m going to try and fix this up and get a build out hopefully later today when I get back to the home office. 

A note to self is to always build this with a java 8 jdk for now. An immediate solution would be to run on java 9 or 10. Thanks for spotting this and I’ll get a new build out soon.

Thanks for reporting it and I’ll get a fix out as soon as I can.

**Comment by davetcc** [comment]
I've tried to build using Java 8 but the UI code is using some Java 9 features. Rather than attempt to revert everything, it's probably better to move forward my plan to package the application as an MSI on windows and App on macOS. That way anyone not able to get the latest Java can run the packaged version without thinking about what's installed.

I'm going to come back to this in the morning and evaluate both options.

**Comment by davetcc** [comment]
The java packager looks very easy to use, it will build platform installers on windows, and an app for macOS, if it turns out even half as easy as it looks, then there should be quick turnaround on this.

**Comment by wilhelmzeuschner** [comment]
Making an .exe for Windows sounds like a good idea.

**Comment by davetcc** [comment]
Fix for this will be:
1. setup module support in project to reduce size of distribution.
2. make a windows MSI installer for the application using javapackager maven plugin
3. make a MacOS disk image that can be dragged to applications

**Comment by davetcc** [comment]
See release 0.6, now has Windows and MacOS native distributions with JRE included.
